services:
  app:
    image: ${DOCKER_USERNAME}/${DOCKER_IMAGE}:${IMAGE_TAG:-latest}
    container_name: posit-app
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-docker}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TOKEN_EXPIRATION : "1209600000"

      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY:-unused}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY:-unused}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME:-posit-deploy}

    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      # 메인 설정 파일 연결
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # [추가] 스위치 파일이 있는 폴더를 통째로 conf.d에 연결
      # 이렇게 해야 나중에 스크립트로 이 안의 파일을 덮어쓸 수 있습니다.
      - ./nginx/service-url.inc:/etc/nginx/conf.d/service-url.inc
    restart: unless-stopped
    networks:
      - app-network
networks:
  app-network:
    driver: bridge